project:
  type: website

website:
  title: "PHS Package Development Guidance"
  navbar:
    # logo: assets/img/mini-logo
    logo: assets/img/smaller-transparent-mini-logo.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar: 
    style: "floating"
    search: true
    logo: https://github.com/Public-Health-Scotland/phstemplates/blob/main/inst/images/phs-logo.png?raw=true
    contents: 
      - href: pages/r-package-versioning.qmd
        text: "R Package Versioning" 
      - href: pages/tags.qmd
        text: "Git Tags and Releases"
      - href: pages/package-manager.qmd
        text: "POSIT Package Manager"
      - href: pages/recommended-git-workflow.qmd
        text: "Recommended Git Workflow"
format:
  html:
    theme: cosmo
    css: phs_style.css
    toc: true


