---
title: "Guidance for developing PHS R Packages"
---

This is a short guide to versioning and tagging when developing R packages in Public Health Scotland (PHS) that are hosted on Github. The aim is to have to a consistent process that can be followed for those developing PHS R packages.  

## Why do we need this guidance?
PHS is using [Posit Package Manager](https://posit.co/products/enterprise/package-manager){target="_blank"} to host R packages (including PHS R packages) internally and this allows users of Posit Workbench to install packages securely and simply using `install.packages()`. Versioning and tagging have implications on Posit Package Manager, depending on how it has been set up for hosting PHS R packages which are being developed on Github. The desired result of developing packages according to this guidance is that users always have access to the latest stable release and are not missing out on any important developments when they install PHS R packages.

## Who is this guidance for?
This guidance is for developers and maintainers of PHS R packages. It is also for those interested in developing PHS R packages or those that want to learn to do this. It is assumed that the reader has some pre-existing knowledge regarding Git and developing R packages.

## What this guidance does not cover
This guidance only discusses particular aspects of R package development and Git and is **not** a general guide to either of these.  

For a comprehensive guide to developing R packages, please see the [R Packages book](https://r-pkgs.org){target="_blank"}.  

To learn more about Git, please see, for example, the [Pro Git](https://git-scm.com/book/en/v2){target="_blank"} book, [Happy Git and GitHub for the useR](https://happygitwithr.com){target="_blank"} or [git - the simple guide](https://rogerdudler.github.io/git-guide){target="_blank"}.
