

## Commits vs Tags

There are two ways for Posit Package Manager to pick up updates from R packages on Github (not applicable to CRAN packages): “tags” or “commits”. Commits mode is based on all commits made to a specified Git branch, while tags mode is based on Git tags that flag new releases in the package repository. 

Commit mode is recommended for bleeding edge repositories, whereas tag mode is suitable for exposing stable releases of packages.

A package sourced from a single Git repository can only be set up with one of the two modes – if you want to use both commits and tags for the same package, two separate Git sources would need to be set up. 

### Commits and Tags Behavior for R Packages

- **Commits**: The package gets updated on Posit Package Manager each time a new commit is made to the specified branch. The package version is updated automatically with the commit time-stamp reflected at the end of the version number. This guarantees the version number for each new commit will be higher than the previous version number.  E.g. phsstyles is on version 0.1.1, however the version number created by Posit Package Manager is 0.1.1.0.0.0.1654859281. 

- **Tags**: The package gets updated on Posit Package Manager each time a Git tag is used in the repository. The package version is defined in the package`s Description file, corresponding to the name of the tag. 
If two tags reference the same version, preference is given to the newer tag. If a newer tag references an older version than a prior tag, the new tag is built as an archived package. If a tag is removed from a Git endpoint, any packages already built for that tag remain.

Check if PHS POSIT Package Manager is using tags or commits by searching the package name at https://ppm.publichealthscotland.org/client/#/repos/3/packages/
